[package]
name = "aethel-wasm"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
authors = { workspace = true }
rust-version = { workspace = true }

[dependencies]
aethel-ir = { path = "../aethel-ir" }
aethel-runtime = { path = "../aethel-runtime" }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
wasmtime = { version = "45", default-features = false, features = [
    "std",
    "cranelift",
    "runtime",
    "component-model",
    "async",
    "wat",
] }