[package]
name = "aethel-testkit"
version = { workspace = true }
edition = "2021"
license = { workspace = true }
authors = { workspace = true }
rust-version = { workspace = true }

[dependencies]
aethel-syntax = { path = "../aethel-syntax" }
aethel-hir = { path = "../aethel-hir" }
aethel-check = { path = "../aethel-check" }
insta = { workspace = true }
pretty_assertions = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
tempfile = "3.10"